//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_two
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exhibits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exhibits()
        {
            this.ExhibitionExhibit = new HashSet<ExhibitionExhibit>();
        }
    
        public int ExhibitId { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public Nullable<int> YearCreated { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExhibitionExhibit> ExhibitionExhibit { get; set; }
    }
}
